# Generated by Django 2.0.7 on 2018-10-03 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='开始计算')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=100, verbose_name='等级名称')),
                ('total_bet', models.BigIntegerField(verbose_name='历史投注')),
                ('gold', models.IntegerField(verbose_name='晋级彩金')),
                ('week_bet', models.IntegerField(verbose_name='周需投注')),
                ('week_salary', models.IntegerField(verbose_name='每周俸禄')),
            ],
            options={
                'verbose_name_plural': '等级管理',
                'verbose_name': '等级管理',
            },
        ),
        migrations.CreateModel(
            name='TotalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100, verbose_name='会员账号')),
                ('total_bet', models.IntegerField(verbose_name='投注金额(总)')),
                ('total_gold', models.IntegerField(verbose_name='等级礼金(总)')),
                ('total_week_salary', models.IntegerField(verbose_name='周俸禄(总)')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salary.Grade')),
            ],
            options={
                'verbose_name_plural': '会员统计',
                'verbose_name': '会员统计',
            },
        ),
        migrations.CreateModel(
            name='WeekData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_name', models.CharField(max_length=100, verbose_name='周期名称')),
                ('serial', models.IntegerField(verbose_name='排序字段')),
            ],
            options={
                'verbose_name_plural': '周期管理',
                'verbose_name': '周期管理',
            },
        ),
        migrations.CreateModel(
            name='WeekRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100, verbose_name='会员账号')),
                ('week_amount', models.IntegerField(default=1, verbose_name='投注金额')),
                ('gold', models.IntegerField(default=0, verbose_name='晋级彩金')),
                ('week_salary', models.IntegerField(default=0, verbose_name='周俸禄')),
                ('downgrade', models.BooleanField(default=False, verbose_name='是否降级')),
                ('compute', models.BooleanField(default=False, verbose_name='是否计算')),
                ('week', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salary.WeekData')),
            ],
            options={
                'verbose_name_plural': '会员投注',
                'verbose_name': '会员投注',
            },
        ),
    ]
