# Generated by Django 2.0.7 on 2018-10-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalrecord',
            name='total_bet',
            field=models.BigIntegerField(verbose_name='投注金额(总)'),
        ),
        migrations.AlterField(
            model_name='weekrecord',
            name='week_amount',
            field=models.BigIntegerField(default=1, verbose_name='投注金额'),
        ),
    ]
