# Generated by Django 2.0.7 on 2019-06-24 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_auto_20181005_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekrecord',
            name='downgrade',
        ),
    ]
